
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - image: vault:1.6.1
          name: vault
          ports:
            - containerPort: 9100
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: media_lake_vault
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: 0.0.0.0:9100
            
            # For seeding
            - name: VAULT_TOKEN
              value: media_lake_vault
            - name: VAULT_ADDR
              value: http://localhost:9100
            - name: VAULT_API_ADDR
              value: http://localhost:9100

            - name: DatabaseOptions__ConnectionString
              value: Host=core-api-postgres-service;Port=5432;Database=postgres;Username=postgres;Password=pa55word
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 15
                    vault secrets enable -path='media-lake-vault-core' -version=2 kv
                    vault kv put media-lake-vault-core/DatabaseOptions ConnectionString=$DatabaseOptions__ConnectionString
          resources:
            limits:
              memory: 256Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"
