apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-volume
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
          name: elasticsearch
          readinessProbe:
            tcpSocket:
              port: 9200
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 240
          ports:
            - containerPort: 9200
          env:
            - name: node.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
            - name: xpack.monitoring.enabled
              value: "true"
            - name: xpack.watcher.enabled
              value: "false"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data 
          resources:
            limits:
              memory: 1024Mi
              cpu: "0.4"
            requests:
              memory: 1024Mi
              cpu: "0.4"
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-volume
