
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: users
      component: api
  template:
    metadata:
      labels:
        app: users
        component: api
    spec:
      containers:
        - image: k8s_media_lake_users_api:latest
          imagePullPolicy: Never
          name: users-api
          ports:
            - containerPort: 8200
          env:
            - name: UrlsOptions__GatewayApiUrl
              value: http://users-api-service #used for openid information receiving. TODO: rename variable name
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8200
            - name: DatabaseOptions__ConnectionString
              value: Host=users-api-postgres-service;Port=5432;Database=postgres;Username=postgres;Password=pa55word
            - name: KafkaOptions__BootstrapServers
              value: kafka-service:9092

            - name: ElasticsearchOptions__ConnectionString
              value: http://elasticsearch-service:9200
          resources:
            limits:
              memory: 1024Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"
