apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: gateway-api
    component: api
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway-api-virtual-service
spec:
  hosts:
    - gateway-api-service
  # http:
  #   - match:
  #     - uri:
  #         prefix: /*
  #     rewrite:
  #       uri: /api
  #     route:
  #   - destination:
  #       host: gateway-api-service
  http:
    - route:
        - destination:
            host: gateway-api-service