version: '3.4'

services:
  # Databases
  media_lake_core_db:
    container_name: media_lake_learn_db
    image: postgres:13.4
    restart: on-failure
    ports:
      - 7433:5432
    networks:
      - media-lake-core-network
    env_file:
      - ../.env/core.env
    volumes:
      - media-lake-core-db-data:/var/lib/postgresql/data

  media_lake_users_db:
    image: postgres:13.4
    container_name: media_lake_users_db
    restart: on-failure
    ports:
      - 7434:5432
    networks:
      - media-lake-users-network
    env_file:
      - ../.env/users.env
    volumes:
      - media-lake-users-db-data:/var/lib/postgresql/data

  # Gateway API
  media_lake_gateway_api:
    container_name: media_lake_gateway_api
    build: 
      context: ../backend/GatewayApi
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - media-lake-core-network
      - media-lake-users-network
    links:
      - media_lake_users_api:media-lake-users-api
    environment:
      - Services__Hosts__Core=http://host.docker.internal:8100
      - Services__Hosts__Users=http://media-lake-users-api:8200

  # Users API
  media_lake_users_api:
    container_name: media_lake_users_api
    build: 
      context: ../backend/Users
    restart: on-failure
    ports:
      - 8200:8200
    networks:
      - media-lake-users-network
    environment:
      - UrlsOptions__GatewayApiUrl=http://localhost:8200
      - ASPNETCORE_URLS=http://0.0.0.0:8200
    env_file:
      - ../.env/users.env
  
volumes:
  media-lake-core-db-data:
    driver: local
  media-lake-users-db-data:
    driver: local

networks:
  media-lake-core-network:
    driver: bridge
  media-lake-users-network:
    driver: bridge
