apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zookeeper-virtual-service
spec:
  hosts:
    - zookeeper-service
  http:
    - route:
        - destination:
            host: zookeeper-service