
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: core
      component: api
  template:
    metadata:
      labels:
        app: core
        component: api
    spec:
      containers:
        - image: k8s_media_lake_core_api:latest
          imagePullPolicy: Never
          name: core-api
          ports:
            - containerPort: 8100
          env:
            - name: UrlsOptions__GatewayApiUrl
              value: http://users-api-service #used for openid information receiving. TODO: rename variable name
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8100

            - name: KafkaOptions__BootstrapServers
              value: kafka-service:9000
            - name: KafkaOptions__GroupId
              value: media-lake-core

            - name: VaultOptions__Address
              value: http://vault-service:9100
            - name: VaultOptions__Token
              value: media_lake_vault
            - name: VaultOptions__MountPoint
              value: media-lake-vault-core

            - name: ElasticsearchOptions__ConnectionString
              value: http://elasticsearch-service:9200
          resources:
            limits:
              memory: 512Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"
