version: '3.4'

services:
  # Databases
  media_lake_core_db:
    container_name: media_lake_core_db
    image: postgres:13.4
    restart: on-failure
    ports:
      - 7433:5432
    networks:
      - media-lake-core-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa55word # I know it is bad, but security issues are not important now
      PGDATA: /var/lib/postgresql/data
    volumes:
      - media-lake-core-db-data:/var/lib/postgresql/data

  media_lake_users_db:
    image: postgres:13.4
    container_name: media_lake_users_db
    restart: on-failure
    ports:
      - 7434:5432
    networks:
      - media-lake-users-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa55word
      PGDATA: /var/lib/postgresql/data
    volumes:
      - media-lake-users-db-data:/var/lib/postgresql/data

  # Kafka
  media_lake_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: media_lake_kafka
    depends_on:
      - media_lake_kafka_zookeeper
    ports:
      - 9092:9092
      - 9000:9000
    networks:
      - media-lake-kafka-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: media_lake_kafka_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://media_lake_kafka:9092,CONNECTIONS_FROM_HOST://localhost:9000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  media_lake_kafka_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: media_lake_kafka_zookeeper
    ports:
      - 9001:2181
    networks:
      - media-lake-kafka-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  media_lake_kafka_ui:
    image: provectuslabs/kafka-ui
    container_name: media_lake_kafka_ui
    restart: on-failure
    ports:
      - 9002:8080
    networks:
      - media-lake-kafka-network
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=media_lake_kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=media_lake_kafka_zookeeper:2181

  # Vault
  media_lake_vault:
    image: vault:1.6.1
    container_name: media_lake_vault
    restart: on-failure
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: media_lake_vault
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:9100
      VAULT_TOKEN: media_lake_vault
      # VAULT_ADDRESS: http://0.0.0.0:9100
    ports:
      - "9100:9100"
    cap_add:
      - IPC_LOCK
    networks:
      - media-lake-vault-network
    volumes:
      - ../../.vault:/.vault

  media_lake_vault_core_seeder:
    image: vault:1.6.1
    container_name: media_lake_vault_core_seeder
    restart: on-failure
    depends_on:
      - media_lake_vault
    networks:
      - media-lake-vault-network
    command:
      - /bin/sh
      - -c
      - |
        vault secrets enable -path='media-lake-vault-core' -version=2 kv
        vault kv put media-lake-vault-core/DatabaseOptions ConnectionString=$$DatabaseOptions__ConnectionString
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: media_lake_vault
      VAULT_ADDR: http://media_lake_vault:9100
      VAULT_API_ADDR: http://media_lake_vault:9100
      VAULT_TOKEN: media_lake_vault
      DatabaseOptions__ConnectionString: Host=media_lake_core_db;Port=5432;Database=postgres;Username=postgres;Password=pa55word

  # Elastichearch
  media_lake_elastichearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: media_lake_elastichearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9210:9200
    networks:
      - media-lake-elastichearch-network
    volumes:
      - media-lake-elastichearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name=media_lake_elastichearch
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  media_lake_kibana:
    image: kibana:7.8.1
    container_name: media_lake_kibana
    depends_on:
        - media_lake_elastichearch
    ports:
        - 9220:5601
    networks:
        - media-lake-elastichearch-network
    environment:
        - ELASTICSEARCH_HOSTS=http://media_lake_elastichearch:9200

  # Gateway API
  media_lake_gateway_api:
    container_name: media_lake_gateway_api
    build: 
      context: ../../backend/GatewayApi
    restart: on-failure
    depends_on:
      - media_lake_elastichearch
    ports:
      - 8000:8000
    networks:
      - media-lake-core-network
      - media-lake-users-network
      - media-lake-elastichearch-network
    links:
      - media_lake_users_api:media-lake-users-api
      - media_lake_core_api:media-lake-core-api
    environment:
      - Services__Hosts__Core=http://media-lake-core-api:8100
      - Services__Hosts__Users=http://media-lake-users-api:8200
      - ElasticsearchOptions__ConnectionString=http://media_lake_elastichearch:9200

  # Users API
  media_lake_users_api:
    container_name: media_lake_users_api
    build: 
      context: ../../backend/Users
    restart: on-failure
    depends_on:
      - media_lake_kafka
      - media_lake_users_db
      - media_lake_elastichearch
    ports:
      - 8200:8200
    networks:
      - media-lake-users-network
      - media-lake-kafka-network
      - media-lake-elastichearch-network
    environment:
      - UrlsOptions__GatewayApiUrl=http://localhost:8200
      - ASPNETCORE_URLS=http://0.0.0.0:8200
      - KafkaOptions__BootstrapServers=media_lake_kafka:9092
      - DatabaseOptions__ConnectionString=Host=media_lake_users_db;Port=5432;Database=postgres;Username=postgres;Password=pa55word
      - ElasticsearchOptions__ConnectionString=http://media_lake_elastichearch:9200

  # Core API
  media_lake_core_api:
    container_name: media_lake_core_api
    build: 
      context: ../../backend/Core
    restart: on-failure
    depends_on:
      - media_lake_kafka
      - media_lake_core_db
      - media_lake_elastichearch
    ports:
      - 8100:8100
    networks:
      - media-lake-core-network
      - media-lake-kafka-network
      - media-lake-vault-network
      - media-lake-elastichearch-network
    environment:
      - UrlsOptions__GatewayApiUrl=http://localhost:8100
      - ASPNETCORE_URLS=http://0.0.0.0:8100
      - KafkaOptions__BootstrapServers=media_lake_kafka:9092
      - KafkaOptions__GroupId=media-lake-core
      - VaultOptions__Address=http://media_lake_vault:9100
      - VaultOptions__Token=media_lake_vault
      - VaultOptions__MountPoint=media-lake-vault-core
      - ElasticsearchOptions__ConnectionString=http://media_lake_elastichearch:9200
      - AWSOptions__Environment=yaroslav-local
      - AWSOptions__Region=eu-central-1
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
  
volumes:
  media-lake-core-db-data:
    driver: local
  media-lake-users-db-data:
    driver: local
  media-lake-elastichearch-data:
    driver: local

networks:
  media-lake-core-network:
    driver: bridge
  media-lake-users-network:
    driver: bridge
  media-lake-kafka-network:
    driver: bridge
  media-lake-vault-network:
    driver: bridge
  media-lake-elastichearch-network:
    driver: bridge
